eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8082
spring:
  application:
    name: service-authentication
  datasource:
    url: jdbc:oracle:thin://localhost:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: jfm
    password: jfm
